import { SITE_URL } from '@/constants';
import { taskAreaRecipients } from '@/db/adminQueries';
import { listRecentDone } from '@/db/taskQueries';
import { notifyGroup } from '@/lib/notify';
import { composeDigestEmail } from '@/lib/digestEmail';
import { logSystemActivity } from '@/lib/activityLog';
import { runCron } from '@/lib/cronRun';
import {
  dayKeyIn,
  dayStartIn,
  shiftDayKey,
  STUDIO_TZ,
} from '@/lib/calendar';

/**
 * Monday-morning studio digest (vercel.json cron, 15:00 UTC = 8am PDT /
 * 7am PST — DST drift accepted). One email to every tasks-area member covering
 * the PREVIOUS Vancouver Mon–Sun week — the exact week, not a rolling 7 days,
 * so Monday-morning work never leaks in and a late send never drops Sunday.
 * Runs inside runCron (src/lib/cronRun.ts), which owns the CRON_SECRET check
 * and stamps the run's outcome for /admin/monitoring; sends happen inline —
 * nobody is waiting on this response, so after() would buy nothing.
 *
 * This file owns the WINDOW and the recipients. Everything the email says is
 * src/lib/digestEmail.ts, which folds the rows once and returns the subject,
 * the plain-text body and the HTML together so the two renderings cannot
 * disagree. It is guard-free so scripts/check-digest-email.mts can pin the
 * real folds, which is why this route does no counting of its own any more.
 */

export const dynamic = 'force-dynamic';

// Display-only label for a YYYY-MM-DD day key ('Aug 4'). The key already IS
// the Vancouver calendar day, so pinning UTC here is exact, not tz math.
const DAY_LABEL = new Intl.DateTimeFormat('en-US', {
  month: 'short',
  day: 'numeric',
  timeZone: 'UTC',
});
const labelKey = (key: string) => DAY_LABEL.format(new Date(`${key}T00:00:00Z`));

/** The email letterhead, at the public ROOT rather than under /images/ (which
 *  is served immutable, so content changes there would need a new filename).
 *  Generated by scripts/generate-dashboard-icons.mjs. */
const DIGEST_LOGO_FILE = 'perseus-wordmark-email.png';

export async function GET(request: Request) {
  return runCron('weekly-digest', request, async () => {
    // STUDIO_TZ, not a viewer's: this is one studio Mon–Sun week emailed to
    // everybody, so the window must be identical in every copy.
    const todayKey = dayKeyIn(STUDIO_TZ, new Date());
    // Weekday of the Vancouver calendar day (0 = Sunday) → this week's Monday.
    const dow = new Date(`${todayKey}T00:00:00Z`).getUTCDay();
    const thisMonday = shiftDayKey(todayKey, -((dow + 6) % 7));
    const weekStart = shiftDayKey(thisMonday, -7);

    const rows = await listRecentDone({
      since: dayStartIn(STUDIO_TZ, weekStart),
      until: dayStartIn(STUDIO_TZ, thisMonday),
      limit: 500,
    });
    if (rows.length === 0) {
      return {
        body: { sent: false, reason: 'nothing completed last week' },
        summary: 'Nothing completed last week, so no digest sent',
      };
    }

    const recipients = await taskAreaRecipients();
    if (recipients.length === 0) {
      return {
        body: { sent: false, reason: 'no recipients' },
        summary: 'Nobody holds the tasks area. No digest sent',
      };
    }

    const rangeLabel = `${labelKey(weekStart)} – ${labelKey(shiftDayKey(thisMonday, -1))}`;
    // TaskBoardRow satisfies DigestRow structurally, so the rows go straight in.
    const { subject, text, html, week } = composeDigestEmail({
      rows,
      rangeLabel,
      // The DIGEST view, not a filtered list: it is the in-app rendering of
      // this very email (done work grouped by day and member), so the reader
      // lands on the same shape they were just looking at rather than on a
      // board tab whose own window disagrees with the week above it.
      boardUrl: `${SITE_URL}/admin/tasks?view=digest`,
      // Built by hand rather than through resolveImageUrl, which only passes
      // through paths under /images/ and would silently swap anything else for
      // the AVIF placeholder — an image no mail client can render.
      logoUrl: `${SITE_URL}/${DIGEST_LOGO_FILE}`,
    });

    // One door, so the digest email and its push twin are driven from the
    // SAME recipient list — nobody can be on one and off the other. The email
    // carries the rollups and each member's biggest items; the push carries
    // two counts, because it lands on a lock screen.
    const delivery = await notifyGroup({
      recipients,
      mail: { subject, text, html },
      push: {
        kind: 'digest',
        tasks: week.deliverables,
        members: week.members.length,
      },
    });
    // A cron leaves no other trace. "The Monday digest silently stopped
    // three weeks ago" is invisible to every signal this app has — an
    // activity row per run makes the ABSENCE of a run visible on /admin/logs.
    logSystemActivity('System', {
      area: 'cron',
      entity: 'cron',
      entityId: null,
      entityName: 'weekly-digest',
      action: 'send',
      summary: `Sent the weekly digest to ${recipients.length} people`,
      payload: {
        count: rows.length,
        meta: { recipients: recipients.length, pushed: delivery.pushed },
      },
    });

    return {
      body: {
        sent: delivery.emailed,
        tasks: rows.length,
        recipients: recipients.length,
        pushed: delivery.pushed,
      },
      summary: delivery.emailed
        ? `Sent the digest to ${recipients.length} people · ${rows.length} tasks`
        : 'The digest email did not send',
      warnings: delivery.emailed ? [] : ['digest email failed'],
    };
  });
}
