export const blogPosts = [
  {
    id: 1,
    slug: "design-systems-2-0-brand-os",
    title: "Design Systems 2.0: From UI Kits to Brand Operating Systems",
    href: "/blogs/design-systems-2-0-brand-os",
    description:
      "Design systems have outgrown static UI kits. We outline how to evolve toward a brand operating system—tokens, multi‑brand theming, motion primitives, content patterns, and governance. See how to connect Figma libraries to code pipelines, version and test tokens, and measure adoption with real KPIs. Includes rollout playbooks for product teams, marketing sites, and campaigns without breaking velocity.",
    imageUrl: "/logo-black.png",
    date: "Sep 14, 2025",
    datetime: "2025-09-14",
    category: { title: "Design Systems", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Design Systems Team",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "Design Systems 2.0: Brand Operating Systems",
      description:
        "Evolve UI kits into a brand OS: tokens, multi‑brand theming, motion, content patterns, and governance. Connect Figma to code, version tokens, and measure adoption.",
      canonicalPath: "/blogs/design-systems-2-0-brand-os",
      ogTitle: "Design Systems 2.0: Brand Operating Systems",
      ogDescription:
        "Evolve UI kits into a brand OS with tokens, theming, motion, and governance.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "design systems",
        "brand operating system",
        "design tokens",
        "multi-brand theming",
        "Figma",
        "governance",
      ],
      schema: {
        "@type": "Article",
        headline: "Design Systems 2.0: Brand Operating Systems",
        datePublished: "2025-09-14",
        dateModified: "2025-09-14",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/design-systems-2-0-brand-os",
        },
      },
    },
  },
  {
    id: 2,
    slug: "motion-for-meaning-real-time",
    title: "Motion for Meaning: Building Brands with 2D/3D and Real‑Time",
    href: "/blogs/motion-for-meaning-real-time",
    description:
      "Motion is language. We share how we design motion systems that scale—from Lottie and CSS to Blender and real‑time engines—without sacrificing performance or accessibility. Learn pipelines for concept → previs → render → handoff, file‑size budgets, and how to bring interaction, physics, and sound together to create memorable brand moments across web, product, and experiential.",
    imageUrl: "/logo-black.png",
    date: "Aug 26, 2025",
    datetime: "2025-08-26",
    category: { title: "Motion & 3D", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Motion Design Lead",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "Motion for Meaning: 2D/3D & Real‑Time",
      description:
        "Design motion systems that scale—from Lottie & CSS to Blender and real‑time—without sacrificing performance or accessibility. Pipelines, budgets, and clean handoff.",
      canonicalPath: "/blogs/motion-for-meaning-real-time",
      ogTitle: "Motion for Meaning: 2D/3D & Real‑Time",
      ogDescription:
        "Systems for brand motion across 2D/3D and real‑time with performance in mind.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "motion design",
        "real-time",
        "Blender",
        "Lottie",
        "accessibility",
        "brand motion",
      ],
      schema: {
        "@type": "Article",
        headline: "Motion for Meaning: 2D/3D & Real‑Time",
        datePublished: "2025-08-26",
        dateModified: "2025-08-26",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/motion-for-meaning-real-time",
        },
      },
    },
  },
  {
    id: 3,
    slug: "web-experiences-that-sell",
    title: "Web Experiences That Sell: Strategy → UX → Craft → Analytics Loop",
    href: "/blogs/web-experiences-that-sell",
    description:
      "Your site is a revenue system, not a brochure. We map the end‑to‑end process: ICP research, messaging frameworks, information architecture, performance budgets, accessibility, and micro‑interactions that guide attention. See our blueprint for headless CMS setups, component libraries, QA, and an analytics loop that turns insight into continuous A/B improvements.",
    imageUrl: "/logo-black.png",
    date: "Jul 30, 2025",
    datetime: "2025-07-30",
    category: { title: "Web", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Experience Design Director",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "Web Experiences That Sell: Strategy to Analytics",
      description:
        "Treat your site as a revenue system. ICP research, messaging, IA, performance, accessibility, micro‑interactions, headless CMS, component libraries, QA, and A/B loops.",
      canonicalPath: "/blogs/web-experiences-that-sell",
      ogTitle: "Web Experiences That Sell: Strategy to Analytics",
      ogDescription:
        "Blueprints for high‑converting web experiences from strategy to analytics.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "web strategy",
        "conversion",
        "headless CMS",
        "accessibility",
        "A/B testing",
        "information architecture",
      ],
      schema: {
        "@type": "Article",
        headline: "Web Experiences That Sell: Strategy to Analytics",
        datePublished: "2025-07-30",
        dateModified: "2025-07-30",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/web-experiences-that-sell",
        },
      },
    },
  },
  {
    id: 4,
    slug: "ai-in-the-studio-assistive-not-autonomous",
    title: "AI in the Studio: Assistive, Not Autonomous",
    href: "/blogs/ai-in-the-studio-assistive-not-autonomous",
    description:
      "Practical ways AI augments creative work without diluting authorship. We cover ideation accelerators (moodboards, alt text, colorways), prompt libraries, guardrails for brand voice, and provenance controls. Explore workflows that respect privacy and licensing while speeding production across copy, image, and motion—plus how to evaluate models and measure impact on cycle time.",
    imageUrl: "/logo-black.png",
    date: "Sep 5, 2025",
    datetime: "2025-09-05",
    category: { title: "Ops & AI", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Creative Operations",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "AI in the Studio: Assistive, Not Autonomous",
      description:
        "Practical AI that augments creative work without diluting authorship. Prompt libraries, brand guardrails, provenance, privacy, licensing, and measurable cycle‑time impact.",
      canonicalPath: "/blogs/ai-in-the-studio-assistive-not-autonomous",
      ogTitle: "AI in the Studio: Assistive, Not Autonomous",
      ogDescription:
        "Workflows that keep authorship while using AI across copy, image, and motion.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "AI workflows",
        "brand guardrails",
        "provenance",
        "privacy",
        "licensing",
        "prompt libraries",
      ],
      schema: {
        "@type": "Article",
        headline: "AI in the Studio: Assistive, Not Autonomous",
        datePublished: "2025-09-05",
        dateModified: "2025-09-05",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/ai-in-the-studio-assistive-not-autonomous",
        },
      },
    },
  },
  {
    id: 5,
    slug: "pitch-decks-that-close",
    title: "Pitch Decks That Close: Narrative, Evidence, and Visual Rhythm",
    href: "/blogs/pitch-decks-that-close",
    description:
      "Great decks sell a story viewers can repeat. We break down structure (problem → opportunity → solution → proof), slide choreography, typographic systems, and data visualization that persuades. See templates for modular case studies, demo flows, and motion cues that align presenters and visuals—plus a checklist for rehearsal and stakeholder reviews.",
    imageUrl: "/logo-black.png",
    date: "Jun 18, 2025",
    datetime: "2025-06-18",
    category: { title: "Strategy", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Strategy Team",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "Pitch Decks That Close: Narrative & Proof",
      description:
        "Structure, slide choreography, type systems, and persuasive data viz. Templates for case studies, demo flows, motion cues, and a checklist for rehearsal and reviews.",
      canonicalPath: "/blogs/pitch-decks-that-close",
      ogTitle: "Pitch Decks That Close: Narrative & Proof",
      ogDescription: "Frameworks to build decks that persuade and close.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "pitch decks",
        "storytelling",
        "data visualization",
        "presentation design",
        "case studies",
        "rehearsal checklist",
      ],
      schema: {
        "@type": "Article",
        headline: "Pitch Decks That Close: Narrative & Proof",
        datePublished: "2025-06-18",
        dateModified: "2025-06-18",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/pitch-decks-that-close",
        },
      },
    },
  },
  {
    id: 6,
    slug: "rebrands-without-the-chaos",
    title: "Rebrands Without the Chaos: Orchestrating Multi‑Market Rollouts",
    href: "/blogs/rebrands-without-the-chaos",
    description:
      "Rebrands fail when rollout lags strategy. We share the operations backbone: asset governance, naming updates, domains and redirects, signage, social, and templated content at scale. Learn change‑management tactics, training plans, and a command‑center approach to track creative, legal, and IT workstreams with clear go‑live criteria and post‑launch metrics.",
    imageUrl: "/logo-black.png",
    date: "May 21, 2025",
    datetime: "2025-05-21",
    category: { title: "Brand", href: "/blogs" },
    author: {
      name: "Perseus Creative Studio",
      role: "Program Management",
      href: "/",
      imageUrl: "/logo-black.png",
    },
    seo: {
      title: "Rebrands Without the Chaos: Rollouts",
      description:
        "Asset governance, naming, domains/redirects, signage, social, and templated content at scale. Change management, training plans, and go‑live criteria with metrics.",
      canonicalPath: "/blogs/rebrands-without-the-chaos",
      ogTitle: "Rebrands Without the Chaos: Rollouts",
      ogDescription:
        "Operational playbooks for rebrands across markets without chaos.",
      ogImage: "/logo-black.png",
      ogType: "article",
      twitterCard: "summary_large_image",
      robots: "index,follow",
      keywords: [
        "rebrand rollout",
        "asset governance",
        "redirects",
        "change management",
        "training",
        "go-live criteria",
      ],
      schema: {
        "@type": "Article",
        headline: "Rebrands Without the Chaos: Rollouts",
        datePublished: "2025-05-21",
        dateModified: "2025-05-21",
        author: { "@type": "Organization", name: "Perseus Creative Studio" },
        publisher: { "@type": "Organization", name: "Perseus Creative Studio" },
        image: ["/logo-black.png"],
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "/blogs/rebrands-without-the-chaos",
        },
      },
    },
  },
];
