export const websiteCustomerLogos = [
  {
    id: 1,
    src: "https://html.tailus.io/blocks/customers/nvidia.svg",
    alt: "Nvidia Logo",
    href: "https://www.nvidia.com/",
    height: 20,
    width: 10,
  },
  {
    id: 2,
    src: "https://html.tailus.io/blocks/customers/column.svg",
    alt: "Column Logo",
    href: "https://column.com/",
    height: 16,
    width: 10,
  },
  {
    id: 3,
    src: "https://html.tailus.io/blocks/customers/github.svg",
    alt: "GitHub Logo",
    href: "https://github.com/",
    height: 16,
    width: 10,
  },
  {
    id: 4,
    src: "https://html.tailus.io/blocks/customers/nike.svg",
    alt: "Nike Logo",
    href: "https://www.nike.com/",
    height: 20,
    width: 10,
  },
  {
    id: 5,
    src: "https://html.tailus.io/blocks/customers/lemonsqueezy.svg",
    alt: "Lemon Squeezy Logo",
    href: "https://www.lemonsqueezy.com/",
    height: 20,
    width: 10,
  },
  {
    id: 6,
    src: "https://html.tailus.io/blocks/customers/laravel.svg",
    alt: "Laravel Logo",
    href: "https://laravel.com/",
    height: 16,
    width: 10,
  },
  {
    id: 7,
    src: "https://html.tailus.io/blocks/customers/lilly.svg",
    alt: "Lilly Logo",
    href: "https://www.lilly.com/",
    height: 28,
    width: 10,
  },
  {
    id: 8,
    src: "https://html.tailus.io/blocks/customers/openai.svg",
    alt: "OpenAI Logo",
    href: "https://www.openai.com/",
    height: 20,
    width: 10,
  },
];
