<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"
    doctype-system="about:legacy-compat" />

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex" />
        <title>Perseus Creative Studio — XML Sitemap</title>
        <style>
          :root {
            --ink: #141414;
            --bone: #f5f2ec;
            --ember: #c4502e;
            --stone: #8a8378;
            --line: rgba(20, 20, 20, 0.1);
          }
          * { box-sizing: border-box; }
          body {
            margin: 0;
            background: var(--bone);
            color: var(--ink);
            font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI",
              Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.5;
            -webkit-font-smoothing: antialiased;
          }
          .wrap { max-width: 1100px; margin: 0 auto; padding: 56px 24px 80px; }
          header { border-bottom: 1px solid var(--line); padding-bottom: 28px; }
          .eyebrow {
            font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
            font-size: 11px;
            letter-spacing: 0.22em;
            text-transform: uppercase;
            color: var(--ember);
            margin: 0 0 12px;
          }
          h1 {
            font-size: clamp(28px, 5vw, 44px);
            letter-spacing: -0.03em;
            line-height: 1.05;
            margin: 0;
          }
          .meta {
            margin-top: 16px;
            font-size: 14px;
            color: var(--stone);
          }
          .meta strong { color: var(--ink); font-variant-numeric: tabular-nums; }
          .count-pill {
            display: inline-flex;
            align-items: baseline;
            gap: 6px;
            margin-top: 18px;
            padding: 7px 14px;
            border: 1px solid var(--line);
            border-radius: 999px;
            background: #fff;
            font-size: 13px;
          }
          .count-pill b { font-size: 15px; font-variant-numeric: tabular-nums; }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 32px;
            background: #fff;
            border: 1px solid var(--line);
            border-radius: 14px;
            overflow: hidden;
            font-size: 14px;
          }
          thead th {
            text-align: left;
            font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
            font-size: 10px;
            letter-spacing: 0.16em;
            text-transform: uppercase;
            color: var(--stone);
            padding: 14px 18px;
            border-bottom: 1px solid var(--line);
            background: var(--bone);
          }
          tbody td { padding: 13px 18px; border-bottom: 1px solid var(--line); vertical-align: top; }
          tbody tr:last-child td { border-bottom: 0; }
          tbody tr:hover td { background: rgba(196, 80, 46, 0.04); }
          td.num { color: var(--stone); font-variant-numeric: tabular-nums; width: 48px; }
          td.tag { font-variant-numeric: tabular-nums; color: var(--stone); white-space: nowrap; }
          a { color: var(--ink); text-decoration: none; border-bottom: 1px solid var(--ember); word-break: break-all; }
          a:hover { color: var(--ember); }
          footer { margin-top: 36px; font-size: 12px; color: var(--stone); }
        </style>
      </head>
      <body>
        <div class="wrap">
          <xsl:apply-templates select="s:sitemapindex" />
          <xsl:apply-templates select="s:urlset" />
          <footer>
            Generated by Perseus Creative Studio · This page is for humans;
            crawlers read the underlying XML.
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>

  <!-- Sitemap index: a table of child sitemaps, with a per-label URL count
       and grand total read from the `section:` / `sitemap-total:` comments. -->
  <xsl:template match="s:sitemapindex">
    <xsl:variable name="total"
      select="normalize-space(substring-after(/comment()[contains(., 'sitemap-total:')], 'sitemap-total:'))" />
    <header>
      <p class="eyebrow">XML Sitemap · Index</p>
      <h1>Sitemap index</h1>
      <p class="meta">This index links every child sitemap on the site.</p>
      <span class="count-pill">
        <b><xsl:value-of select="count(s:sitemap)" /></b> sitemaps
      </span>
      <xsl:if test="$total != ''">
        <span class="count-pill" style="margin-left: 8px;">
          <b><xsl:value-of select="$total" /></b> URLs total
        </span>
      </xsl:if>
    </header>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Sitemap</th>
          <th>Section</th>
          <th>URLs</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="s:sitemap">
          <xsl:variable name="meta" select="preceding-sibling::comment()[1]" />
          <tr>
            <td class="num"><xsl:value-of select="position()" /></td>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc" /></a></td>
            <td class="tag">
              <xsl:value-of
                select="normalize-space(substring-before(substring-after($meta, 'section:'), '|'))" />
            </td>
            <td class="tag">
              <xsl:value-of select="normalize-space(substring-after($meta, '|'))" />
            </td>
            <td class="tag"><xsl:value-of select="s:lastmod" /></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

  <!-- URL set: a table of page URLs. The content-type name comes from the
       `sitemap-label:` comment each child sitemap emits; falls back to "URLs". -->
  <xsl:template match="s:urlset">
    <xsl:variable name="rawLabel"
      select="normalize-space(substring-after(/comment()[contains(., 'sitemap-label:')], 'sitemap-label:'))" />
    <xsl:variable name="label">
      <xsl:choose>
        <xsl:when test="$rawLabel != ''"><xsl:value-of select="$rawLabel" /></xsl:when>
        <xsl:otherwise>URLs</xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <header>
      <p class="eyebrow">XML Sitemap · <xsl:value-of select="$label" /></p>
      <h1>Sitemap</h1>
      <p class="meta">Canonical, index-worthy URLs in this section.</p>
      <span class="count-pill">
        <b><xsl:value-of select="count(s:url)" /></b>
        <xsl:text> </xsl:text>
        <xsl:value-of select="$label" />
      </span>
    </header>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>URL</th>
          <th>Priority</th>
          <th>Change</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="s:url">
          <tr>
            <td class="num"><xsl:value-of select="position()" /></td>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc" /></a></td>
            <td class="tag"><xsl:value-of select="s:priority" /></td>
            <td class="tag"><xsl:value-of select="s:changefreq" /></td>
            <td class="tag"><xsl:value-of select="s:lastmod" /></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>
</xsl:stylesheet>
